x-bot: &bot
  build: .
  image: agh-community-bot
  restart: unless-stopped
  environment:
    PYTHONUNBUFFERED: 1
  volumes:
    - ${ENV_FILE_PATH:-./.env}:/app/.env:ro
    - ${ANECDOTES_FILE_PATH:-./anecdotes.txt}:/app/anecdotes.txt:ro

x-postgres: &postgres
  image: postgres:alpine
  restart: unless-stopped
  environment:
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_DB: ${POSTGRES_DB}
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  bot-prod:
    <<: *bot
    profiles:
      - prod
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-prod/${POSTGRES_DB}}
    depends_on:
      postgres-prod:
        condition: service_healthy

  postgres-prod:
    <<: *postgres
    profiles:
      - prod
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-dev:
    <<: *postgres
    profiles:
      - dev
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "6543:5432"

volumes:
  postgres-data:
