services:
  agh-community-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: agh-community-bot
    restart: unless-stopped
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}}
    volumes:
      - ${ENV_FILE_PATH:-./.env}:/app/.env:ro
      - ${ANECDOTES_FILE_PATH:-./anecdotes.txt}:/app/anecdotes.txt:ro

  redis:
    image: redis:alpine
    profiles: [ "redis" ]
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:alpine
    profiles: [ "postgres" ]
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  postgres-data:
